version: "3"
services:
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    network_mode: "host"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  mario:
    image: pengbai/docker-supermario
    container_name: mario
    ports:
      - "8600:8080"
